(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], en=document.documentElement.lang==='en';
let version='logo',surface='light';
function logo(){const stage=$('.cg-logo-stage');stage.dataset.surface=surface;stage.dataset.version=version;$('#cg-logo').src=`/COPLANAR/assets/coplanar-guide/${version}-${surface==='light'?'dark':'light'}.svg`;$$('button[data-logo]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.logo===version)));$$('button[data-surface]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.surface===surface)));}
$$('button[data-logo]').forEach(b=>b.addEventListener('click',()=>{version=b.dataset.logo;logo()}));$$('button[data-surface]').forEach(b=>b.addEventListener('click',()=>{surface=b.dataset.surface;logo()}));
let toastTimer;function toast(msg){const box=$('#cg-toast');box.textContent=msg;box.dataset.visible='true';clearTimeout(toastTimer);toastTimer=setTimeout(()=>{box.dataset.visible='false'},3000)}
$$('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{const code=b.dataset.copy;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(code)}else{const field=document.createElement('textarea');field.value=code;field.style.cssText='position:fixed;left:-9999px';document.body.append(field);field.select();const ok=document.execCommand('copy');field.remove();b.focus();if(!ok)throw Error('copy failed')}toast(en?`${code} copied`:`${code} copiado`)}catch{toast(en?`Copy this code: ${code}`:`Copie este código: ${code}`)}}));
function specimen(){const size=$('#cg-type-size').value;$('#cg-specimen').textContent=$('#cg-type-input').value||'Coplanar';$('#cg-specimen').style.fontWeight=$('#cg-type-weight').value;$('#cg-specimen').style.fontSize=`${size}px`;$('#cg-size-label').textContent=`${size} px`}
['#cg-type-input','#cg-type-weight','#cg-type-size'].forEach(s=>$(s).addEventListener('input',specimen));
$$('button[data-format]').forEach(b=>b.addEventListener('click',()=>{$('.cg-system-demo').dataset.format=b.dataset.format;$$('button[data-format]').forEach(v=>v.setAttribute('aria-pressed',String(v===b)))}));$('#cg-grid-toggle').addEventListener('change',e=>{$('.cg-grid-overlay').hidden=!e.target.checked});
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);if(visible.length){$$('[data-chapter]').forEach(a=>{if(a.dataset.chapter===visible[0].target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}},{rootMargin:'-120px 0px -55% 0px',threshold:0});$$('.cg-section').forEach(s=>observer.observe(s))}
function language(){const hash=location.hash;$$('.cg-language').forEach(a=>{a.href=a.getAttribute('href').split('#')[0]+hash})}window.addEventListener('hashchange',language);language();
const dialog=$('#cg-lightbox');let trigger,oldOverflow;$$('.cg-expand').forEach(b=>b.addEventListener('click',()=>{trigger=b;const img=dialog.querySelector('img');img.src=b.dataset.image;img.alt=b.querySelector('img').alt;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();$('#cg-close').focus()}));$('#cg-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>{document.body.style.overflow=oldOverflow||'';trigger?.focus()});
})();
(()=>{if(!('IntersectionObserver'in window)||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('cg-enter');reveal.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.cg-section-heading,.cg-intro-grid,.cg-logo-stage,.cg-type-top,.cg-system-stage,.cg-app-grid figure,.cg-palette').forEach((el,i)=>{el.classList.add('cg-reveal','cg-wait');el.style.setProperty('--cg-delay',(i%3)*80+'ms');if(el.matches('.cg-palette'))el.querySelectorAll('.cg-color').forEach((color,j)=>color.style.setProperty('--cg-delay',j*110+'ms'));reveal.observe(el)});})();
